[package]
name = "mpd-shuffler"
version = "0.1.0"
edition = "2021"
description = "Randomly shuffle your MPD library"
readme = "README.md"
license = "MIT"
keywords = ["mpd", "shuffle"]
homepage = "https://github.com/awused/mpd-shuffler"
repository = "https://github.com/awused/mpd-shuffler"

[dependencies]
awconf = { git = "https://github.com/awused/awconf" }
aw-shuffle = { git = "https://github.com/awused/aw-shuffle", features = [ "rocks" ] }
futures-util = { version = "0.3.17", default-features = false, features = [ "sink" ] }
mpd_protocol = { version = "=0.12.1", features = [ "async" ] }
once_cell = "1.8.0"
regex = "1.5.4"
serde = { version = "1.0", default-features = false, features = [ "derive" ] }
signal-hook = "0.3.9"
signal-hook-tokio = { version = "0.3.0", features = [ "futures-v0_3" ] }
structopt = "0.3"
tokio = { version = "1.13", features = [ "macros", "process", "rt", "sync", "time" ] }
tokio-util = { version = "0.6.9", default-features = false, features = [ "codec" ] }
